### ISSUE TITLE
Problem with SquaredError

### ISSUE THREAD

**Issue by mdmdmd9876** [Microsoft/CNTK#1518]
Hi, 
I wrote a c++ program that aims to evaluate pictures with an already trained model, that i load with the Function::LoadModel() function with help of the CNTKLibrary. Afterwards I prepare the input with the Value::CreateBatch() function 
and evaluate it with Function::Evaluate().
When I run it though I get the following error:
What() is:The shape of input operands for the SquaredError operation should have at most one axis
I don't understand this error. I am not even using the SquaredError() function and when looking at the code of the CNTK functions I use, none of them uses SquaredError(). Furthermore when I load for example the linear Regression model from the first BrainScript tutorial it runs perfectly, so i guess it is somehow connected to the dimension of the output. 
When and through what is the SquaredError() function called? 
Thanks a lot in advance :)

Edit: the problem already occurs when loading the model. My strongest guess is, that LoadModel() does only support label vectors and not label matrices with dimensions like 2x10 or something like that. Is that the mistake?

**Comment by zhouwangzw** [comment]
@mdmdmd9876 Thanks for reporting the issue. This should now be fixed in the lastest master. Could you please have a try? If you use CTNK Library from binary download package or Nuget package, you will have to wait for the next release, which is available probably end of this week. 
If you still have the issue, please let us know.

Sorry for the inconvenience!
Zhou

**Comment by mdmdmd9876** [comment]
Firstly thank you for your reply.
I am still getting the error though:
What() is:SquaredError mse: The shape of input operands for the
SquaredError operation should have at most one axis
I think the problem is that the SquaredError function in the CNTKLibrary only supports, like the error says, inputs with one axis. In one of my models for example I am comparing two pictures with each other so the label size is something like 96x96, which works perfectly when doing it via the terminal and the write/test command (as far as i know), but not when evaluation with the CNTKLibrary. 
I also created a feature Request a view days ago concerning that matter. 
#1558 

Best regards
Maximilian

**Comment by sayanpa** [comment]
Hi Maximilian, assuming the answer on #1558 helped. Closing this issue for now. Please reopen new issues if you need help.
