### ISSUE TITLE
Getting Started with CNTK in C# on Xamarin Workbooks

### ISSUE THREAD

**Issue by larcai** [Microsoft/CNTK#2588]
I created initial workbooks on how to get started with CNTK in C#.
I used xamarin workbooks...  Maybe one day we will have Xamarin workbooks in Azure...
[Cognibooks](https://github.com/larcai/cognibooks)

**Getting Started**
![Getting Started](https://github.com/larcai/cognibooks/blob/master/cntk/screenshot.cntk.gs1.png?raw=true)

**Logistic Regression**
![Logistic Regression](https://github.com/larcai/cognibooks/blob/master/cntk/screenshot.cntk.log_reg1.png?raw=true)

**Comment by whitmark** [comment]
This could be quite useful, thanks for sharing.  I am having trouble getting past the DeviceDescriptor, any suggestions?

![image](https://user-images.githubusercontent.com/8396992/32495347-59eac1a0-c393-11e7-814f-612ea35b7b23.png)

**Comment by larcai** [comment]
Make sure you have the unmanaged CNTK dlls in your system path.  Should solve that error.

**Comment by whitmark** [comment]
@larcai I was still getting the error so I switched to the loaded NuGet package and added the system path to no avail.  Any other ideas?  Thanks.

![image](https://user-images.githubusercontent.com/8396992/32978432-396f9aec-cc10-11e7-9f8e-4a44eead0e0c.png)

**Comment by whitmark** [comment]
@larcai I was able to get the sample code working with the Nuget CNTK.CPUOnly 2.3.0 (since the Nuget CNTK.GPU 2.3.0 package was not yet available).  Thanks again for your initial post!

![image](https://user-images.githubusercontent.com/8396992/33174474-31f6acdc-d026-11e7-9200-70f391cf5fef.png)

**Comment by larcai** [comment]
I'm glad it helped.  I actually downloaded the GPU version and extracted the zip on my machine.  [CNTK for Windows v.2.2 GPU with 1bit-SGD](https://cntk.ai/dlw1-2.2.html)
