### ISSUE TITLE
Virtualenv dll placement rules are broken, causing VS debug failures.

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#2780]
Here is what the Python Tools team has to say about the issue:
>So we believe the problem here is that CNTK is installing DLLs into the wrong location. We've chatted with them separately about it, so it may be fixed in one of their updates.

>The DLLs should be alongside the module (DLL) that loads them, not the executable. Presumably they chose that path to work with a regular install of Python or an Anaconda env and did not test it with a virtualenv, which has a different layout.

>They should fix their wheel (and we've already told them this, so a newer version might be fixed already?).

>The wheels that their docs point to were built on May 31st, so it's possible that they've implemented a fix but not released it yet. Or maybe they have, but haven't updated the installation page (linked above).

>So it looks like they've known about it since May or even earlier. I'll try to find out who it is we need to send a reminder to.

Please, fix this finally.

https://github.com/Microsoft/PTVS/issues/2528
https://github.com/Microsoft/PTVS/issues/2806

**Comment by manikjindal** [comment]
Thanks for reporting. It has been fixed in master and will be available in the next release.

**Comment by JoeyCarson** [comment]
Has this issue been fixed?  I'm still having the same trouble working a conda virtualenv.  The installation in base is able to find the dll without any problems.  But inside any virtualenv, it's never able to find the dll.  I am running cntk-gpu-2.6.
