### ISSUE TITLE
Build failure AllReduceData

### ISSUE THREAD

**Issue by melrobin** [Microsoft/CNTK#3004]
I receive the following error on build even thought he configure line has the option --mpi=off

Source/CNTKv2LibraryDll/DistributedCommunicator.cpp:532:114: error: ‘MPI_MAX’ was not declared in this scope
             AllReduceData<SparseIndexType>(pCol2BlockId, pCol2BlockId, sbcInfo.numCols, nullptr, aggregateOnCPU, MPI_MAX, true);

**Comment by KeDengMS** [comment]
Thanks for reporting this bug. DistributedCommunicator should not be built with MPI off. We'll work on a fix.

**Comment by KeDengMS** [comment]
[Fixed](https://github.com/Microsoft/CNTK/commit/7215678c552c835d138baa7a73c41c99982a63e2)

**Comment by melrobin** [comment]
This issue still exists.  Here is the complete line:
creating .build/Source/CNTKv2LibraryDll/proto/onnx/CNTKToONNX.o for Linux with build type release
g++ -c Source/CNTKv2LibraryDll/proto/onnx/CNTKToONNX.cpp -o .build/Source/CNTKv2LibraryDll/proto/onnx/CNTKToONNX.o -DHAS_MPI=0 -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DCUDA_NO_HALF -D__CUDA_NO_HALF_OPERATORS__ -DUSE_CUDNN -DUSE_NCCL -DUSE_MKL -DUSE_MKLDNN -DNDEBUG -DNO_SYNC -DASGD_PARALLEL_SUPPORT  -DCNTK_VERSION="2.4" -DCNTK_VERSION_BANNER="2.4+" -DCNTK_COMPONENT_VERSION="2.4" -DUSE_ZIP -msse4.1 -mssse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/CNTKv2LibraryDll -ISource/CNTKv2LibraryDll/API -ISource/CNTKv2LibraryDll/proto -ISource/../Examples/Extensibility/CPP -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -ISource/PerformanceProfilerDll -I/usr/local/protobuf-3.1.0/include -I/usr/local/cuda/include -I/usr/local/cub -I/usr/local/cuda-9.0/include -I/usr/local/cuda/include -I/usr/local/include -I/usr/local/mklml/include -I/usr/local/boost-1.60.0/include -I/usr/include -I/usr/lib/libzip/include -I/usr/local/include -I/usr/local/include -ISource/Multiverso/include -ITests/EndToEndTests/CNTKv2Library/Common -I/usr/local/boost-1.60.0/include -ISource/Readers/CNTKTextFormatReader -MD -MP -MF .build/Source/CNTKv2LibraryDll/proto/onnx/CNTKToONNX.d
Source/CNTKv2LibraryDll/DistributedCommunicator.cpp: In member function ‘virtual void CNTK::MPICommunicatorImpl::AllReduceSparseBlockColumn(std::vector<std::shared_ptr<CNTK::NDArrayView> >&)’:
Source/CNTKv2LibraryDll/DistributedCommunicator.cpp:532:114: error: ‘MPI_MAX’ was not declared in this scope
             AllReduceData<SparseIndexType>(pCol2BlockId, pCol2BlockId, sbcInfo.numCols, nullptr, aggregateOnCPU, MPI_MAX, true);

**Comment by KeDengMS** [comment]
Leave a comment

**Comment by melrobin** [comment]
This is now fixed....closing.

**Comment by melrobin** [comment]
Closed too soon.  Sorry.

**Comment by melrobin** [comment]
mpi=no now works.
