### ISSUE TITLE
errors when compile CNTK 

### ISSUE THREAD

**Issue by jren2012** [Microsoft/CNTK#92]
When I compile this toolkit, I met the problem below. I will appreciate any help. 

=-----------------------------------------------------------=
creating /home/jren/Repos/CNTK/build/release/.build/Source/Readers/LMSequenceReader/SequenceReader.o for with build type release
mpic++ -c Source/Readers/LMSequenceReader/SequenceReader.cpp -o /home/jren/Repos/CNTK/build/release/.build/Source/Readers/LMSequenceReader/SequenceReader.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -DCPUONLY -DUSE_ACML -DNDEBUG -msse3 -std=c++0x -std=c++11 -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/opt/acml5.3.1/ifort64_mp/include -I/home/jren/opencv-3.0.0/include -MD -MP -MF /home/jren/Repos/CNTK/build/release/.build/Source/Readers/LMSequenceReader/SequenceReader.d
cc1plus: all warnings being treated as errors
Makefile:555: recipe for target **# '/home/jren/Repos/CNTK/build/release/.build/Source/Readers/ReaderLib/ReaderShim.o' failed
make[1]: *** [/home/jren/Repos/CNTK/build/release/.build/Source/Readers/ReaderLib/ReaderShim.o] **Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/jren/Repos/CNTK'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by frankseide** [comment]
Hi Jun, we don’t see this. Would you mind posting your compiler version information?

**Comment by Ark-kun** [comment]
Fixed by this PR: https://github.com/Microsoft/CNTK/pull/93

**Comment by jren2012** [comment]
Ubuntu 15.04， OpenCV 3.0.0，cuda 7.5, and acml-5-3-1-ifort-64bit, openmpi-1.10.1, cub-1.4.1 

I'm wondering if it is the problem of cuda. Does cntk still can't support cuda 7.5?

**Comment by Ark-kun** [comment]
The problem with ReaderShim was that you the default argument values belong to the header, not .cpp. Not sure why that DID compile for anyone.

**Comment by mradmila** [comment]
It looks like this is fixed by fix for issue #93. If not, can you please reopen with latest information.
